- name: read mount file
  shell: cat /proc/mounts
  changed_when: false
  register: mnt_point

- name: if mnt_point valid
  when:
    mount_point == true
  failed_when: mnt_point.stdout.find('/var/lib/docker\s') == -1
  debug: msg="mount point not valid"
  ignore_errors: yes

- name: check docker group
  shell: getent group docker
  changed_when: false
  register: docker_grp
  when:
    docker_group == true
  failed_when: docker_grp.stdout.find('') == -1
  ignore_errors: yes

- name: Check that the cis.rules exists
  stat:
    path: /etc/audit/rules.d/cis.rules
  register: cis_conf
  when:
    auditd_conf == true

- name: create cis.rules if not exist
  file:
    path: "/etc/audit/rules.d/cis.rules"
    state: touch
  when:
    not cis_conf.stat.exists

- name: get text from cis.rules
  shell: cat /etc/audit/audit.rules 
  register: cis_rules_text
  when:
    auditd_conf == true

    # 1.1.3
- name: 1.1.3 Ensure auditing is configured for the Docker daemon
  when:
    auditd_conf == true and cis_rules_text.stdout.find('-w /usr/bin/dockerd -k docker') == -1
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/cis.rules
    line: -w /usr/bin/dockerd -k docker
  ignore_errors: yes

  #1.1.4
- name: 1.1.4 Ensure auditing is configured for Docker files and directories-/run/containerd
  when:
    auditd_conf == true and cis_rules_text.stdout.find('-a exit,always -F path=/run/containerd -F perm=war -k docker') == -1
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/cis.rules
    line: -a exit,always -F path=/run/containerd -F perm=war -k docker
  ignore_errors: yes


  #1.1.5
- name: 1.1.5 Ensure auditing is configured for Docker files and directories-/var/lib/docker
  when:
    auditd_conf == true and cis_rules_text.stdout.find('-a exit,always -F path=/var/lib/docker -F perm=war -k docker') == -1
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/cis.rules
    line: -a exit,always -F path=/var/lib/docker -F perm=war -k docker
  ignore_errors: yes

  #1.1.6
- name: 1.1.6 Ensure auditing is configured for Docker files and directories-/etc/docker
  when:
    auditd_conf == true and cis_rules_text.stdout.find('-w /etc/docker -k docker') == -1
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/cis.rules
    line: -w /etc/docker -k docker
  ignore_errors: yes
  
  #1.1.7
- name: 1.1.7 Ensure auditing is configured for Docker files and directories-docker.service
  when:
    auditd_conf == true and cis_rules_text.stdout.find('-w /usr/lib/systemd/system/docker.service -k docker') == -1
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/cis.rules
    line: -w /usr/lib/systemd/system/docker.service -k docker 
  ignore_errors: yes


  
  #1.1.8
- name: 1.1.8 Ensure auditing is configured for Docker files and directories-containerd.sock
  when:
    auditd_conf == true and cis_rules_text.stdout.find('-w /run/containerd/containerd.sock -k docker') == -1
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/cis.rules
    line: -w /run/containerd/containerd.sock -k docker 
  ignore_errors: yes
 
#1.1.9
- name: 1.1.9 Ensure auditing is configured for Docker files and directories-docker.socket 
  when:
    auditd_conf == true and cis_rules_text.stdout.find('-w /var/run/docker.sock -k docker') == -1
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/cis.rules
    line: -w /var/run/docker.sock -k docker 
  ignore_errors: yes


 #1.1.10
- name: 1.1.10 Ensure auditing is configured for Docker files and directories-/etc/default/docker
  when:
    auditd_conf == true and cis_rules_text.stdout.find('-w /etc/default/docker -k docker') == -1
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/cis.rules
    line: -w /etc/default/docker -k docker 
  ignore_errors: yes
 
#1.1.11
- name: 1.1.11 Ensure auditing is configured for Docker files and directories-/etc/docker/daemon.json
  when:
    auditd_conf == true and cis_rules_text.stdout.find('-w /etc/docker/daemon.json -k docker') == -1
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/cis.rules
    line: -w /etc/docker/daemon.json -k docker 
  ignore_errors: yes
 
  #1.1.12
- name: 1.1.12 Ensure auditing is configured for Docker files and directories-/etc/containerd/config.toml
  when:
    auditd_conf == true and cis_rules_text.stdout.find('-w /etc/containerd/config.toml -k docker') == -1
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/cis.rules
    line: -w /etc/containerd/config.toml -k docker 
  ignore_errors: yes

  #1.1.13
- name: 1.1.13 Ensure auditing is configured for Docker files and directories-/etc/sysconfig/docker
  when:
    auditd_conf == true and cis_rules_text.stdout.find('-w /etc/sysconfig/docker -k docker') == -1
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/cis.rules
    line: -w /etc/sysconfig/docker -k docker 
  ignore_errors: yes
  
  #1.1.14
- name: 1.1.14 Ensure auditing is configured for Docker files and directories-/usr/bin/containerd
  when:
    auditd_conf == true and cis_rules_text.stdout.find('-w /usr/bin/containerd -k docker') == -1
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/cis.rules
    line: -w /usr/bin/containerd -k docker 
  ignore_errors: yes


  #1.1.15
- name: 1.1.15 Ensure auditing is configured for Docker files and directories-/usr/bin/containerd-shim
  when:
    auditd_conf == true and cis_rules_text.stdout.find('-w /usr/bin/containerd-shim -k docker') == -1
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/cis.rules
    line: -w /usr/bin/containerd-shim -k docker
  ignore_errors: yes

  #1.1.16
- name: 1.1.16 Ensure auditing is configured for Docker files and directories-/usr/bin/containerd-shim-runc-v1
  when:
    auditd_conf == true and cis_rules_text.stdout.find('-w /usr/bin/containerd-shim-runc-v1 -k docker') == -1
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/cis.rules
    line: -w /usr/bin/containerd-shim-runc-v1 -k docker
  ignore_errors: yes


  #1.1.17
- name: 1.1.17 Ensure auditing is configured for Docker files and directories-/usr/bin/containerd-shim-runc-v2
  when:
    auditd_conf == true and cis_rules_text.stdout.find('-w /usr/bin/containerd-shim-runc-v2 -k docker') == -1
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/cis.rules
    line: -w /usr/bin/containerd-shim-runc-v2 -k docker 
  ignore_errors: yes

  #1.1.18
- name: 1.1.18 Ensure auditing is configured for Docker files and directories-/usr/bin/runc
  when:
    auditd_conf == true and cis_rules_text.stdout.find('-w /usr/bin/runc -k docker') == -1
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/cis.rules
    line: -w /usr/bin/runc -k docker 
  ignore_errors: yes

  #1.2.2
- name: 1.2.2 Ensure that the version of Docker is up to date
  shell: "docker -v | cut -d ' ' -f 3 | cut -d ',' -f 1" 
  register: version
  
- name: help for 1.2.2  
  debug: msg="Docker version-{{version.stdout}}"
  











  #------------------------------------------------
- name: Check that the somefile.conf exists
  stat:
    path: /etc/fstab
